Import('env')
env = env.Clone()

env.UnitTest(target = 'translation_service_wtest',
             source = ['translation_service_wtest.cpp'],
             LIBS=['gtest_main', 'gmock', 'gtest', 'pthread']
             )
