Import('env')
env = env.Clone()

env.UnitTest(target = 'tokenizer_bb_test',
             source = ['tokenizer_bb_test.cpp' , 'tokenizer.cpp'],
             LIBS=['gtest_main', 'gmock', 'gtest', 'pthread']
             )

