Import('env')
env = env.Clone()

env.UnitTest(target = 'and_doc_list_wtest',
             source = ['and_doc_list_wtest.cpp',
                       'and_doc_list.cpp'],
             LIBS=env['gmock_libs']
             )

